version: '2'

services:

  reverse_nginx:
    image: nginx:alpine
    #restart: always
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - /root/cephos-aart-config/nginx-reverse/www:/var/www/
      - /root/cephos-aart-config/nginx-reverse/SSL:/var/ssl
      - /root/cephos-aart-config/nginx-reverse/htaccess:/var/htaccess
      - /root/cephos-aart-config/nginx-reverse/nginx:/etc/nginx

  shiny:
    image: floe/shiny-custom
    volumes:
      - /aart:/root/cephos-art


