version: '2'

services:

  reverse_nginx:
    image: nginx:alpine
    #restart: always
    ports:
      - "8080:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - /root/cephos-aart-config/nginx-reverse/www:/usr/share/nginx/html:ro
      #- /root/cephos-aart-config/nginx-reverse/SSL:/var/ssl
      #- /root/cephos-aart-config/nginx-reverse/htaccess:/var/htaccess
      - /root/cephos-aart-config/nginx-reverse/nginx/:/etc/nginx/
      
  shiny:
    image: floe/shiny-custom
    ports:
      - "80:3838"
    volumes:
      #- /root/cephos-aart-config/shiny/index.html:/srv/shiny-server/index.html
      - /root/cephos-aart:/srv/shiny-server/cephos-aart
      - /srv/shinylog/:/var/log/

